backend:
  name: github
  repo: samypogs/untitled_v2
  branch: master

publish_mode: editorial_workflow

media_folder: "/static/files/"
public_folder: "/files/"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Content Type",
          name: "contentType",
          widget: "hidden",
          default: "blog",
        }
      - { label: "Path", name: "path", widget: "string", default: "title" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Attachment",
          name: "attachments",
          required: false,
          widget: "list",
          fields: [{ name: "filename", label: "Filename", widget: "file" }],
        }
      - {
          label: "Related Post",
          name: "related",
          required: false,
          widget: "list",
          fields:
            [
              {
                name: "post",
                label: "Post",
                widget: "relation",
                collection: "blog",
                searchFields: [name, path, title],
                valueField: path,
              },
            ],
        }

  - name: "pages"
    label: "Pages"
    folder: "src/pages/content"
    create: false
    slug: "{{slug}}"
    fields:
      - {
          label: "Content Type",
          name: "contentType",
          widget: "hidden",
          default: "pages",
        }
      - { label: "Path", name: "path", widget: "hidden", default: "/" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
